spring:
    application:
        name: demo-spring
    datasource: 
        url : jdbc:postgresql://localhost:5433/test
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
    jpa: 
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect


